version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /chaincode/crimerecords
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /benchmarks/caliper
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
