"""Ordered classification rules for ``build_inventory.py``.

The first rule whose ``pattern`` matches a repository-relative path wins. Rules
record the audit's *proposed* action; the moves that were actually performed are
listed in ``trashy/MANIFEST.csv``. Each rule states the evidence for its
decision in ``notes`` so that the inventory can be reviewed row by row.
"""

# Directory names whose contents are collapsed into one inventory row.
COLLAPSE_DIR_NAMES = {"node_modules", "__pycache__", ".nyc_output", "coverage"}
# Path prefixes collapsed into one row (large local payloads with no per-file meaning).
COLLAPSE_PREFIXES = (
    ".venv-qwen-policy",
    "network/organizations/peerOrganizations",
    "network/organizations/ordererOrganizations",
    "network/organizations/fabric-ca",
    "network/channel-artifacts",
    "backend/data/agency-vault",
    "backend/data/dias-reviews",
    "backend/wallets",
    "tmp",
)

T = "move:trashy/"


def rule(pattern, role, classification, action, confidence, notes=""):
    return {"pattern": pattern, "role": role, "classification": classification,
            "action": action, "confidence": confidence, "notes": notes}


RULES = [
    # ---- local environments, dependencies, caches (never published) ----------
    rule(r"(^|/)node_modules/", "installed npm dependencies", "dependency", "keep-ignored", "high",
         "Required by make test; recreated by make install (npm ci from package-lock.json)."),
    rule(r"^\.venv-qwen-policy/", "local MLX Python environment", "local-environment", "keep-ignored", "high",
         "Required by make dias-model and the evaluation scripts; contains absolute paths, so it is not relocatable."),
    rule(r"(^|/)__pycache__/", "Python bytecode cache", "generated-cache", T + "generated/", "high",
         "Regenerated automatically by Python; ignored by .gitignore."),
    rule(r"(^|/)(coverage|\.nyc_output)/", "test coverage output", "generated-cache", "keep-ignored", "high",
         "Rewritten by every chaincode test run; ignored."),
    rule(r"(^|/)\.DS_Store$", "macOS Finder metadata", "generated-cache", "keep-ignored", "high",
         "Recreated by Finder; ignored. Not moved because Finder rewrites it immediately."),
    rule(r"^\.env$", "local environment configuration", "local-secret", "keep-ignored", "high",
         "May hold local secrets; never published. Template is .env.example."),
    rule(r"^network/organizations/(peerOrganizations|ordererOrganizations|fabric-ca)/", "generated Fabric crypto material",
         "local-secret", "keep-ignored", "high", "Generated by make up/seed; contains private keys; ignored."),
    rule(r"^network/channel-artifacts/", "generated channel artifacts", "generated-output", "keep-ignored", "high", "Ignored."),
    rule(r"^backend/data/.*\.pem$", "retired signing private key", "local-secret", "keep-ignored", "high",
         "Private key of the retired AI-organization attestation design; ignored. Recommend the owner delete or rotate it."),
    rule(r"^backend/(data|wallets)/", "backend runtime state", "local-state", "keep-ignored", "high",
         "Wallets, agency vault and off-chain review store; ignored runtime state."),
    rule(r"^\.blockdemo/", "ledger-inspection scratch output", "generated-output", T + "generated/", "high",
         "Written by ledger inspection; ignored by .gitignore (Generated during ledger inspection)."),
    rule(r"^\.bootstrap-logs/", "network bootstrap logs (2026-09-10)", "generated-output", T + "generated/", "medium",
         "Ignored bootstrap logs of the base network; not referenced by any document."),
    rule(r"^tmp/", "scratch renders and extracted reference text", "temporary", T + "temporary/", "high",
         "Ignored scratch space (tmp/ in .gitignore); includes extracted text of third-party papers."),

    # ---- manuscripts -------------------------------------------------------------
    rule(r"^Proof reading/_pre_review_backup/", "backups of the user's Overleaf text before proof-reading",
         "superseded-draft", T + "superseded-paper-drafts/", "high",
         "Backups of the 2026-09-17 Overleaf download; kept for reverting proof-read edits."),
    rule(r"^Proof reading/(main\.tex|sections/|dias-refs\.bib|figures/)", "latest Overleaf manuscript (proof-read 2026-09-17)",
         "canonical-manuscript-source", "canonicalize:papers/final_paper/", "high",
         "Most recent, complete, buildable copy of the user's manuscript; becomes the canonical entry point."),
    rule(r"^Proof reading/", "Overleaf package extras (old PDF, README)", "superseded-draft", T + "superseded-paper-drafts/", "high",
         "main_old.pdf / main_revised.pdf / README_OVERLEAF.txt are builds or package notes, not sources."),
    rule(r"^Proof reading\.zip$", "Overleaf download archive (2026-09-17 08:58)", "duplicate", T + "superseded-paper-drafts/", "high",
         "Byte-identical sources to Proof reading/_pre_review_backup; ignored (*.zip)."),
    rule(r"^DIAS latex paper/", "earlier Overleaf download (2026-09-16)", "superseded-draft", T + "superseded-paper-drafts/", "high",
         "Superseded by the 2026-09-17 download; retains supervisor notes later removed on Overleaf."),
    rule(r"^papers/final_paper/(dias_paper|abstract|introduction|related_work|related_work_TABLE|methodology|methodology_algorithm|"
         r"implementation|evaluation_setup|results|limitations|conclusion|discussion|security_analysis|system_model|"
         r"methodology_decision|methodology_figure|methodology_governance|methodology_v1_full|unique_user_latency_results|"
         r"overleaf_main|DIAS_Implementation_Rewritten|DIAS_Methodology_Rewritten|DIAS_Methodology_Results)\.tex$",
         "agent-written parallel draft of the DIAS paper", "superseded-draft", T + "superseded-paper-drafts/", "medium",
         "13-page repository draft not adopted verbatim by the author; superseded by the Overleaf text."),
    rule(r"^papers/final_paper/dias_paper\.(aux|bbl|blg|log|out|pdf)$", "LaTeX build output of the superseded draft",
         "generated-build", T + "generated/", "high", "Build output; regenerated by tectonic."),
    rule(r"^papers/final_paper/(seal_paper|SEBA_XAI_|seba_xai_|SEAL_latest|Internship_Final_Report|SEBA_Internship|SEBA_XAI_Internship)",
         "predecessor SEAL/SEBA manuscripts and internship deliverables", "obsolete-deliverable", T + "obsolete/seal-era/", "high",
         "Belong to the predecessor SEAL/SEBA paper, not to DIAS."),
    rule(r"^papers/final_paper/(overleaf_sections|tables)/", "inputs of the superseded draft", "superseded-draft",
         T + "superseded-paper-drafts/", "medium", "Only \\input by the superseded draft."),
    rule(r"^papers/final_paper/(DIAS_OVERLEAF_README|DIAS_REWRITE_NOTES)\.md$", "notes about the superseded draft",
         "superseded-draft", T + "superseded-paper-drafts/", "medium", ""),
    rule(r"^papers/final_paper/(dias-refs|related-work-refs|seba-refs)\.bib$", "bibliographies of the superseded draft",
         "superseded-draft", T + "superseded-paper-drafts/", "medium", "Canonical bibliography is the Overleaf dias-refs.bib."),
    rule(r"^papers/final_paper/figures/", "figures of the superseded draft", "superseded-draft", T + "superseded-paper-drafts/", "medium",
         "Not referenced by the canonical manuscript; script-generated figures remain in results/plots."),
    rule(r"^papers/final_paper/artifacts/", "provenance notes of earlier drafts", "historical-evidence", "review", "medium", ""),
    rule(r"^papers/reference_library/manifest\.csv$", "reference download manifest", "canonical-doc", "keep", "high",
         "Provenance of the reference library; used by scripts/download-reference-library.sh."),
    rule(r"^papers/reference_library/", "downloaded third-party papers", "third-party-copyrighted", T + "third-party-papers/", "high",
         "Third-party PDFs; redistribution rights not established. Re-download with scripts/download-reference-library.sh."),
    rule(r"^output/", "generated PDFs and Overleaf packages", "generated-output", T + "generated/", "medium",
         "Builds and export packages of earlier drafts."),
    rule(r"^outputs/", "spreadsheet export of experiment graphs (2026-09-17)", "generated-output", T + "generated/", "medium",
         "Chart workbook exported for Google Sheets; not a source of evidence."),

    # ---- predecessor (SEAL-era) material -------------------------------------------
    rule(r"^paper experiment results/", "SEAL-era five-organization latency/ledger-growth study", "historical-evidence",
         T + "obsolete/seal-era/", "medium", "Evidence for the predecessor paper; not used by the DIAS manuscript."),
    rule(r"^reports/SEBA_.*\.docx$", "SEBA internship report variants", "obsolete-deliverable", T + "obsolete/seal-era/", "high",
         "Internship deliverables of the predecessor project; not DIAS research artifacts."),
    rule(r"^reports/research/.*\.(pdf|html)$", "downloaded third-party papers (related-work research)", "third-party-copyrighted",
         T + "third-party-papers/", "high", "Third-party full texts; redistribution rights not established."),
    rule(r"^LLMxAI/2511\.20284v2\.pdf$", "downloaded third-party paper", "third-party-copyrighted", T + "third-party-papers/", "high",
         "arXiv full text; redistribution rights not established."),
    rule(r"^_figpreview\.svg$", "stray figure preview", "temporary", T + "temporary/", "medium", ""),
    rule(r"^test-refs\.bib$", "placeholder bibliography (one dummy entry)", "temporary", T + "temporary/", "medium", ""),

    # ---- model weights --------------------------------------------------------------
    rule(r"^LLMxAI/experiments/llm_policy_engine/adapters/.*\.safetensors$", "LoRA adapter weights", "model-weights",
         "keep-ignored", "high", "Identified by SHA-256 in run records; weights are not stored in Git."),
    rule(r"^LLMxAI/experiments/llm_policy_engine/adapters/", "adapter configuration and selection records", "canonical-evidence",
         "keep", "high", ""),

    # ---- canonical research pipeline ---------------------------------------------------
    rule(r"^experiments/runs/(2026091[2-9]|2026092)", "DIAS run record", "canonical-evidence", "keep", "high",
         "Raw evidence; never moved."),
    rule(r"^experiments/runs/", "predecessor run record", "historical-evidence", "keep", "high",
         "Raw evidence of earlier iterations; retained in place."),
    rule(r"^experiments/plans/", "experiment plan", "canonical-plan", "keep", "high", ""),
    rule(r"^experiments/dias-finetuning/", "DIAS datasets and training configs", "canonical-data", "keep", "high", ""),
    rule(r"^experiments/dias/", "DIAS experiment scripts", "canonical-source", "keep", "high", ""),
    rule(r"^experiments/", "predecessor experiment scripts and results", "historical-evidence", "keep", "medium", ""),
    rule(r"^results/tables/dias_", "DIAS result table", "canonical-result", "keep", "high", ""),
    rule(r"^results/plots/dias", "DIAS result plot", "canonical-result", "keep", "high", ""),
    rule(r"^results/", "predecessor result table/plot", "historical-evidence", "keep", "medium", ""),
    rule(r"^reports/iteration/", "iteration report", "canonical-report", "keep", "high", ""),
    rule(r"^reports/repository_audit/", "publication-readiness audit", "canonical-report", "keep", "high", ""),
    rule(r"^reports/", "earlier report material", "historical-evidence", "keep", "medium", ""),
    rule(r"^scripts/audit/", "audit tooling", "canonical-source", "keep", "high", ""),

    # ---- application source ----------------------------------------------------------------
    rule(r"^(backend|chaincode|frontend|policies)/.*(test|spec)", "test suite", "canonical-test", "keep", "high", ""),
    rule(r"^(backend|chaincode|frontend|policies|network|scripts)/", "application source/configuration", "canonical-source",
         "keep", "high", ""),
    rule(r"^benchmarks/", "SEAL-era Caliper benchmark workspace", "historical-evidence", "keep", "medium",
         "Makefile caliper-* targets; measures crimechannel, not DIAS."),
    rule(r"^paper-tests/", "SEAL paper experiment harness and results", "historical-evidence", "keep", "medium",
         "Frozen SEAL configuration; not DIAS evidence."),
    rule(r"^solidity-frontend/", "standalone EVM companion prototype", "legacy-prototype", "keep", "medium",
         "Referenced by README; not part of the DIAS paper."),
    rule(r"^LLMxAI/", "SEAL-era standalone LLM runtime and data", "historical-evidence", "keep", "medium",
         "Hosts the DIAS adapter directory referenced by Makefile and run records."),
    rule(r"^docs/", "documentation", "canonical-doc", "keep", "high", ""),
    rule(r"^\.github/", "CI configuration", "canonical-config", "keep", "high", ""),
    rule(r"^(README\.md|AGENTS\.md|LICENSE|CITATION\.cff|CONTRIBUTING\.md|SECURITY\.md|SNAPSHOT\.md|Makefile|\.gitignore|"
         r"\.gitattributes|\.env\.example)$", "root documentation/configuration", "canonical-doc", "keep", "high", ""),
    rule(r"^trashy/", "archived material", "archived", "none", "high", "See trashy/MANIFEST.csv."),
]
